import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Language = "zh" | "en";
type Localized = Record<Language, string>;
type Post = { id: string; date: string; title: Localized; excerpt: Localized; tag: Localized; topics: string[]; minutes: string; featured?: boolean; published?: boolean };
type ArticleBody = { subtitle: Localized; intro: Localized; sections: { heading: Localized; body: Record<Language, string[]>; bullets?: Record<Language, string[]>; figure?: { src: string; caption: Localized } }[]; closing: Localized };

const posts: Post[] = [
  {
    id: "agent-observability",
    date: "2026.08.10",
    title: { zh: "Agent 可观测性：仪表盘不是产出物", en: "Agent Observability: The Dashboard Isn’t the Output" },
    excerpt: { zh: "全链路绿灯，答案是错的。可观测性真正的产出物不是仪表盘，是下一轮评测的数据集。", en: "Every span green, the answer wrong. What observability produces is not a dashboard but the dataset for the next round of evaluation." },
    tag: { zh: "AgentOps", en: "AgentOps" },
    topics: ["agentops", "observability", "evaluation"],
    minutes: "9 min",
    featured: true,
    published: true,
  },
  {
    id: "agent-infra",
    date: "2026.07.28",
    title: { zh: "为什么 Agent Infra 越来越重要", en: "Why Agent Infra Matters More Than Ever" },
    excerpt: { zh: "主循环现在可以买到了。真正的分水岭，是你第一次让 Agent 写生产数据那天。", en: "The main loop is something you buy now. The dividing line is the day you first let an agent write production data." },
    tag: { zh: "Agent Infra", en: "Agent Infra" },
    topics: ["agent-infra", "systems", "governance"],
    minutes: "7 min",
    published: true,
  },
];

const featured = posts.find((post) => post.featured)!;

const copy = {
  zh: { articles: "文章", about: "关于", search: "搜索文章", all: "全部", latest: "最新文章", selected: "精选文章", read: "阅读文章", comingSoon: "即将上线", back: "返回文章列表", contact: "和我聊聊", top: "回到顶部 ↑", aboutLead: "你好，我是 Shihao，一个 INFJ。习惯先把世界安静地看一会儿，再决定留下些什么。", aboutBody: "我相信细微的感受值得被认真对待，也愿意把那些尚未成形的思考，慢慢整理成清晰的文字。", noResults: "没有找到匹配的文章。", essay: "文章" },
  en: { articles: "Writing", about: "About", search: "Search writing", all: "All", latest: "Latest writing", selected: "Selected writing", read: "Read essay", comingSoon: "Coming soon", back: "Back to writing", contact: "Say hello", top: "Back to top ↑", aboutLead: "Hi, I’m Shihao, an INFJ. I tend to sit quietly with the world for a while before deciding what to leave behind.", aboutBody: "I believe subtle feelings deserve attention, and I like turning half-formed thoughts into words with a little more clarity.", noResults: "No matching essays yet.", essay: "Essay" },
} satisfies Record<Language, Record<string, string>>;

const agentInfra = {
  subtitle: { zh: "难度不会消失，它只是换了个地方。", en: "Difficulty doesn’t disappear. It moves." },
  intro: { zh: "一个企业 Agent 最常见的死法，不是答错问题，是答对了一个不该由它回答的问题。而这件事和模型聪不聪明没有任何关系。", en: "The most common way an enterprise agent fails is not by getting the answer wrong. It gets the answer right, for someone who should never have received it. Nothing about that failure has to do with how smart the model is." },
  sections: [
    {
      heading: { zh: "现在死掉的不是模型", en: "What fails now isn’t the model" },
      body: { zh: ["具体是这样：Agent 通过一个服务账号接进了 CRM。为了让它什么都查得到，这个账号的权限被开成了所有用户的并集。于是一个普通销售问它，我们给某个客户的折扣底价是多少，它准确地、带着引用地回答了。模型没出错，检索也没出错。错在这套系统从头到尾不知道提问的人是谁。", "2024 年不会有人讨论这种问题。那时候争的是循环本身能不能收敛：ReAct 会不会原地打转，上下文塞到第几轮开始崩，工具调用能不能稳定吐出合法参数。一个能连续跑十五步不散架的 Agent，本身就算成果。", "这部分现在是买来的。DeepAgents 把规划、文件系统、上下文卸载、子 Agent、Skills 和人工审批打成了一个 Harness；Claude Agent SDK 给你另一套；OpenCode 这类客户端 Agent 连代码仓库的上下文管理都替你想好了。你准备自己写的那个主循环，大概率已经有人写得比你好，而且开源了。", "所以现在停下来的项目，很少是因为模型不够聪明。它们卡在权限，卡在凭据，卡在没人能说清上周三那次错误的写操作是从哪一步来的。"], en: ["Here is the shape of it. An agent is wired into a CRM through a service account. To make sure it can look anything up, that account is given the union of every user’s permissions. A salesperson asks what floor price we gave a particular customer, and the agent answers — accurately, with a citation. The model did not fail. Retrieval did not fail. The system simply never knew who was asking.", "In 2024 nobody would have been discussing that. The argument then was whether the loop converged at all: whether ReAct would spin in place, how many turns before the context fell apart, whether tool calls would reliably emit valid arguments. An agent that ran fifteen steps without coming apart was itself the result.", "That part is now something you buy. DeepAgents packages planning, a file system, context offloading, subagents, skills, and human approval into one harness. Claude Agent SDK gives you another. Client agents like OpenCode have already worked out repository context for you. Whatever main loop you were going to write, someone has probably written a better one and open-sourced it.", "So projects rarely stall now because the model wasn’t clever enough. They stall on permissions, on credentials, on nobody being able to explain which step caused last Wednesday’s bad write."] },
    },
    {
      heading: { zh: "难度守恒", en: "Difficulty is conserved" },
      body: { zh: ["“价值转移到基础设施层”这句话很容易说得像句空话，因为它跳过了原因。", "区别在于两种复杂性。第一种可以在一个仓库里被完整表达出来。Agent 主循环就是这样：说到底是几千行状态机加一组 prompt，边界清楚，跟你在哪家公司无关。这类问题有个特点，只要有人把它写对过一次，就可以被抄一万次。开源特别擅长收敛这种东西，而且只会越来越快。", "第二种没法这么处理。把身份联邦打进一个跑了十五年、当年开发者已经离职的 ERP。让检索层正确继承 SharePoint 里攒了二十年的目录权限。说服安全团队签字，同意一个进程能往生产库写数据。这些工作量不会因为别人做过而减少，因为你面对的不是同一个 ERP，也不是同一个安全团队。", "我倾向于这么区分：Runtime 的难度是智力密度高，Infra 的难度是协商成本高。智力密度可以被一次性攻克，然后免费复制；协商成本每个客户都要重付一遍。开源能替你省掉前者，碰不到后者。", "基础设施并不是突然变得更值钱了。是难度守恒。上面那层被压平以后，下面的部分露出来了。"], en: ["Saying that value moves to the infrastructure layer is easy and usually empty, because it skips the reason.", "There are two kinds of difficulty. The first can be fully expressed inside one repository. The agent loop is like that: a few thousand lines of state machine plus a set of prompts, clear boundaries, no dependence on which company you work at. Solve it correctly once and it can be copied ten thousand times. Open source is extremely good at collapsing this kind of problem, and getting faster at it.", "The second kind resists that. Federating identity into an ERP that has run for fifteen years, whose original developers left. Making retrieval inherit twenty years of accumulated folder permissions in SharePoint. Getting a security team to sign off on a process that can write to a production database. None of this gets smaller because someone else did it, because you are not facing the same ERP or the same security team.", "The distinction I find useful: runtime difficulty is dense in intelligence, infrastructure difficulty is dense in negotiation. Intelligence can be solved once and then copied for free. Negotiation is paid again at every customer. Open source spares you the first and cannot touch the second.", "Infrastructure did not suddenly become more valuable. Difficulty is conserved. The upper layer flattened, and what was underneath became visible."] },
      figure: { src: "/images/agent-architecture-components.png", caption: { zh: "这张图通常被当成组件清单来读。也可以换个读法：Runtime 那一格正在被开源压平，剩下的格子是难度沉降下去的地方。", en: "This diagram usually gets read as a component checklist. Another reading: the runtime box is being flattened by open source, and the remaining boxes are where the difficulty settled." } },
    },
    {
      heading: { zh: "状态所有权在往上走", en: "State ownership keeps moving up" },
      body: { zh: ["客户端 Agent、服务端 Agent、Agent PaaS，这种分法把两件事混在了一起：跑在哪，和怎么卖。", "有一个问题比它们都管用：Session 在谁手里，出事谁背。", "按这个问，是三类。第一类，状态在你自己的目录里，隔离靠操作系统的用户权限，出事你自己收拾，Codex、Claude Code、IDE 里那些 Agent 都算。第二类，企业的技术团队把 Runtime 接进自己的应用，自己实现 SessionStore，自己给 Sandbox 挂工作区，出事这个团队背。第三类，平台统一管 Agent、Environment、Session、权限和调度，出事平台背。", "要紧的不是这三类怎么排序，而是从第一类走到第三类，并不是封装越来越厚，是责任在往上转移。", "举个具体的。你自己用 Claude Code 的时候，要不要让它执行这条 rm，是你当场做的一个判断，判断错了你自己扛。同样这件事放到一个跑着一百个 Agent 的平台上，它必须变成一条可配置、可审计、可回滚的策略，因为不可能让一百个人各自当场判断，也不可能出了事没人能还原过程。", "一个原本属于个人的判断，被迫变成了一个必须被产品化的东西。这就是基础设施出现的位置。", "市场确实在往第三类走，但不是因为第三类更先进，而是因为企业买不了“每个员工自己判断”。这么看，基础设施重不重要就不太算一个观点了，它更像是状态所有权上移之后的一个推论。"], en: ["Client agent, server agent, agent PaaS — that split conflates where something runs with how it is sold.", "One question does more work: who holds the session, and who is liable when it goes wrong.", "By that test there are three kinds. In the first, state lives in your own directory, isolation comes from your OS user account, and you absorb the consequences yourself: Codex, Claude Code, the agents inside your IDE. In the second, an enterprise team wires a runtime into their own application, implements its session store, mounts a workspace for its sandbox, and carries the liability. In the third, a platform governs agents, environments, sessions, permissions, and scheduling, and the platform carries it.", "What matters is not the ordering. It is that moving from the first to the third is not thicker packaging. Responsibility is being transferred upward.", "Concretely: when you run Claude Code yourself, whether to let it execute a particular rm is a judgment you make on the spot, and you clean up your own mistake. Put the same question on a platform running a hundred agents and it has to become a policy that can be configured, audited, and rolled back — because a hundred people cannot each judge on the spot, and nobody can be left unable to reconstruct what happened.", "A judgment that belonged to a person is forced to become a product. That is the position infrastructure occupies.", "The market is moving toward the third kind, not because it is more advanced, but because enterprises cannot buy ‘every employee decides for themselves.’ Whether infrastructure matters is therefore less an opinion than a consequence of state ownership moving up."] },
    },
    {
      heading: { zh: "L3 是一道台阶", en: "L3 is a step, not a slope" },
      body: { zh: ["上面说的是方向。但“越来越重要”是个关于时间的说法，得说清到底是什么在变。企业 Agent 按“能干什么”分四级就够用了：只读问答、生成草稿和分析、审批后执行写操作、在策略边界内自动执行。", "台阶在 L3。Agent 第一次能改变世界的状态，于是两个问题变成硬性的：这次写操作是以谁的身份做的？如果它写错了，谁能在事后精确指出是哪一步、哪个参数？", "答不上来，L3 就上不了线。不是效果不好，是合规不让。MCP Gateway 在 L2 以前是个可选项，跨过 L3 它是开关。", "基础设施投入的那条曲线，在 L3 之前接近平的，跨过 L3 陡然抬起来。", "而需求正在过这道台阶。原因很俗：L1 的 ROI 已经被验证完，也被榨干了。知识问答省的是查资料的十分钟，真正的钱在“少雇一个人做对账”。要去拿那笔钱，Agent 必须能写数据。", "这才是“越来越”的机制。不是基础设施自己在变重要，是需求在往台阶另一边走。四级各自要什么，大致是这样："], en: ["That is a claim about direction. But ‘more than ever’ is a claim about time, and it has to say what actually changed. Four levels are enough to grade an enterprise agent by what it is allowed to do: read-only Q&A, drafts and analysis, writes after approval, autonomous execution inside a policy.", "The step is at L3. For the first time the agent can change the state of the world, which makes two questions mandatory. Under whose identity was this write performed? If it wrote the wrong thing, who can point to the exact step and the exact argument afterward?", "Without answers, L3 does not ship. Not because quality is poor — because compliance says no. An MCP gateway is optional up to L2. Past L3 it is the switch.", "The infrastructure investment curve is nearly flat below L3 and turns sharply upward across it.", "And demand is crossing over. The reason is mundane: L1’s ROI has been proven and also exhausted. Knowledge lookup saves ten minutes of searching. The real money is in not hiring another person to do reconciliation, and to reach it the agent has to write data.", "That is the mechanism behind ‘more than ever.’ Infrastructure is not becoming more important on its own. Demand is walking across the step. Roughly what each level needs:"] },
      bullets: { zh: ["L1，只读问答：一个知识库加一层权限过滤就够了。这时候去建 Sandbox 和 Memory 平台是纯粹的跑偏。", "L2，草稿与分析：开始需要引用和可追溯，因为草稿会被人当成事实用掉。", "L3，审批后执行写操作：台阶在这里。身份传递和证据链从功能变成上线许可。", "L4，在策略边界内自动执行：审批已经不在环上，所有约束必须提前沉到策略里，出事之后只有日志能替你说话。"], en: ["L1, read-only Q&A: a knowledge base and a permission filter are enough. Building a sandbox or a memory platform here is a straight detour.", "L2, drafts and analysis: citations and traceability start to matter, because drafts get used as fact.", "L3, writes after approval: this is the step. Identity propagation and an evidence chain stop being features and become permission to launch.", "L4, autonomous execution inside a policy: approval has left the loop, so every constraint has to be pushed down into the policy in advance, and afterward only the logs can speak for you."] },
    },
    {
      heading: { zh: "五块里只有两块真的属于你", en: "Only two of the five are really yours" },
      body: { zh: ["通常说的 Agent Infra 是五块东西：Sandbox、MCP Gateway、企业知识平台、Memory、AgentOps。这里应该接一个反驳。", "“底层标准化了，所以基础设施层有机会”，这个故事每一波技术浪潮都出现过，而那些故事大部分输给了平台方直接把功能内置。这次的证据也不弱：代码执行、MCP、memory、connector，模型厂商都在自己出，出得还很快。", "这个反驳是对的。但它不是均匀地对。", "分辨的标准是，这个能力锚在谁的资产上。", "锚在模型能力上的会被吃掉。一个能跑 Python 的隔离容器，一个把历史对话按相关性塞回去的 memory 层，这两件事模型厂商比你更该做，也更容易做好。我不看好它们独立成产品。", "锚在客户自己的身份体系和数据边界上的吃不掉。MCP Gateway 要接的是客户的 IdP、客户的 OAuth 配置、客户那套写在表格里的字段级授权规则；企业知识平台要继承的是客户 SharePoint 和几个库里攒了二十年的 ACL。没有哪个模型厂商会去接一万家公司的 AD。", "AgentOps 在中间。Trace 和回放会被平台内置，这部分守不住。但“这次任务有没有真的完成业务目标”必须接客户自己的指标，那部分内置不了。", "回到开头那个折扣底价。它需要的不是把 API 转成 MCP，是身份传递：Agent 调 CRM 的时候带的必须是提问那个销售的身份，而不是一个万能服务账号。这一条就够解释为什么 Gateway 不能是个适配层。", "所以优先级不是五块都做。先做 Gateway 和知识平台，剩下三块能买就买。"], en: ["Agent infra usually means five things: sandbox, MCP gateway, enterprise knowledge, memory, AgentOps. This is where an objection belongs.", "‘The lower layer standardizes, so there is an opening in infrastructure’ is a story every technology wave has produced, and most of those stories lost to the platform vendor shipping the feature itself. The evidence this time is not weak. Code execution, MCP, memory, connectors — model vendors are building all of it, quickly.", "The objection is right. It is not evenly right.", "The test is what a capability is anchored to.", "Anchored to model capability, it gets absorbed. An isolated container that runs Python; a memory layer that ranks past turns and pushes them back in. Model vendors should build those and will build them better. I do not expect either to survive as a standalone product.", "Anchored to the customer’s own identity system and data boundary, it cannot be absorbed. An MCP gateway has to reach their IdP, their OAuth configuration, their field-level authorization rules that live in a spreadsheet. An enterprise knowledge platform has to inherit twenty years of ACLs across their SharePoint and their databases. No model vendor is going to integrate ten thousand companies’ Active Directory.", "AgentOps sits in between. Traces and replay will be built into the platforms and cannot be defended. Whether the task actually achieved a business outcome has to attach to the customer’s own metrics, and that part cannot be.", "Back to the floor price. What that failure needed was not an API-to-MCP adapter. It needed identity propagation: when the agent calls the CRM it must carry the identity of the salesperson who asked, not a service account that can see everything. That one requirement is enough to explain why a gateway cannot be a translation layer.", "So the priority is not all five. Build the gateway and the knowledge platform. Buy the rest if you can."] },
    },
    {
      heading: { zh: "审计是自动化的前提", en: "Auditing comes before automation" },
      body: { zh: ["前面全在讲加约束。代价得放在这里，不然不诚实。", "每一道约束都在收窄 Agent 的可行动空间，也在拉长时延。审批门是这类产品最容易翻车的地方：一个三十秒能做完的任务，加一道人工审批，变成四小时，因为审批的人在开会。ROI 就这么蒸发了。你没省下人力，你只是把“做”换成了“审”，而审的人还得先读懂 Agent 干了什么，这经常比自己动手更慢。", "结论不是“要平衡”。具体一点：审批要按风险分级，不能按动作类型分级。“所有写操作都要审批”是最省心也最致命的一条策略。退五块钱和退五万块钱不该走同一条路，改一个联系人手机号和改一个信用额度也不该。", "还有一个反直觉的地方。可观测性做得好，才有资格少审批。你能在事后精确查出每一步、每个参数、每一次授权是怎么来的，你就敢让更多东西自动跑。审计不是自动化的负担，是它的前提。", "顺着这个，我不太同意把 AgentOps 排在优先级第三位。它该和 Gateway 一起做。不是为了好看的仪表盘，是因为不先把证据链铺好，后面每一次“要不要再放开一点”的讨论都只能靠拍脑袋。"], en: ["Everything above argues for adding constraints. The cost belongs here, or the argument is dishonest.", "Every constraint narrows what the agent can do and lengthens how long it takes. Approval gates are the most common way these products die. A task that takes thirty seconds, plus one human approval, takes four hours, because the approver is in a meeting. The ROI evaporates. You did not save the labor. You converted doing into reviewing, and the reviewer has to first understand what the agent did, which is often slower than doing it themselves.", "The conclusion is not ‘find a balance.’ It is that approval has to be graded by risk, never by action type. ‘All writes require approval’ is the easiest policy to write and the most lethal. A five-dollar refund and a fifty-thousand-dollar refund should not take the same path, and neither should updating a phone number and updating a credit limit.", "There is a less obvious consequence. Good observability is what earns you the right to approve less. If you can reconstruct every step, every argument, and where every authorization came from, you can let more run unattended. Auditing is not a tax on automation. It is the precondition.", "Which is why I would not put AgentOps third in priority. It belongs alongside the gateway — not for the dashboard, but because without an evidence chain in place, every later conversation about loosening a constraint comes down to guesswork."] },
    },
    {
      heading: { zh: "别太早抽象", en: "Don’t abstract too early" },
      body: { zh: ["“不要一上来就建平台”这句话人人都说，落到操作上通常没人执行。", "判断标准可以很粗暴：一个 Infra 组件如果没有两个以上真实使用者，它就不是 Infra，是你的兴趣爱好。", "验收也别用“回答得挺不错”。至少要有任务完成率、人工接管率、越权拦截率，还有单位业务结果的成本。最后这个最容易被跳过，也最容易在半年后变成一张没人解释得清的账单。", "还有一句可能有人不同意：不要因为一个框架“支持多 Agent”就选它。多 Agent 不是默认方案，只有当任务真的能被拆开、而且拆开的收益能被量出来的时候，才值得引入。大部分时候它带来的是调试成本，不是效果。", "至于什么时候可以开始抽象，能执行的版本大概是这样："], en: ["‘Don’t build a platform on day one’ is advice everyone gives and almost nobody follows.", "A blunt test works well enough. An infrastructure component with fewer than two real consumers is not infrastructure. It is your hobby.", "Acceptance should not be ‘the answers look pretty good’ either. At minimum: task completion rate, human takeover rate, blocked-escalation rate, and cost per unit of business outcome. That last one gets skipped most often and turns into a bill nobody can explain six months later.", "One more thing some people will disagree with. Do not pick a framework because it supports multiple agents. Multi-agent is not the default. It earns its place only when the work genuinely decomposes and the gain from decomposing it can be measured. Most of the time what it delivers is debugging cost, not capability.", "As for when to start abstracting, the followable version is roughly this:"] },
      bullets: { zh: ["第一个场景，不抽象任何东西。允许写死，允许难看。", "第二个场景，还是别抽。两个点连不出一条线。", "第三个场景出现同样的连接器、同样的审批逻辑、同样的审计要求，这时候抽，而且只抽重复出现的那部分。"], en: ["First scenario: abstract nothing. Hard-code it. Let it be ugly.", "Second scenario: still don’t. Two points do not make a line.", "Third scenario, when the same connector, the same approval logic, and the same audit requirement show up again: abstract, and only the part that repeated."] },
    },
  ],
  closing: { zh: "如果你现在只跑一个只读的知识问答，这篇文章里的东西你一样都不需要，现在建基础设施是在给一个还不存在的规模做准备。真正的分水岭是你第一次让 Agent 写生产数据那天。在那之前，它是奢侈品；过了那天，它是许可证。", en: "If all you run today is read-only Q&A, you need none of this, and building infrastructure now is preparing for a scale that does not exist yet. The dividing line is the day you first let an agent write production data. Before that day it is a luxury. After it, a license." },
} satisfies ArticleBody;

const agentObservability = {
  subtitle: { zh: "可观测性的产出物不是仪表盘，是数据集。", en: "The output of observability is not a dashboard. It is a dataset." },
  intro: { zh: "上个季度返利政策改过一次，旧版文档没下架。Agent 检索到了旧版，算出一个错了四个点的返点金额，附了引用，格式规整，财务拿这个数去对账了。整条链路上没有一个 span 是红的：检索返回了结果，模型返回了 200，工具调用参数合法，延迟落在 P50。监控告诉你系统是健康的——它说得没错。", en: "The rebate policy changed last quarter and the old document was never taken down. The agent retrieved the old version, computed a rebate that was off by four points, cited its source, and formatted the answer neatly. A finance team reconciled against that number. Nothing in the trace was red: retrieval returned results, the model returned 200, every tool argument validated, latency sat at P50. The monitoring said the system was healthy, and it was right." },
  sections: [
    {
      heading: { zh: "每一步都是 200", en: "Every step returned 200" },
      body: { zh: ["传统可观测性有个隐含前提：失败是可判定的。500、超时、异常栈、队列积压，这些东西不需要人去判断，机器自己就知道出事了。告警之所以能建起来，是因为“错”有一个字段可以对齐。", "Agent 没有这个字段。上面那个错误的返点金额，从系统的角度看，和一次完全正确的回答长得一模一样。你要判断它错了，必须知道当前生效的返利政策是哪一版，而这个知识不在链路里，在业务里。", "第二层麻烦更难受。传统 trace 的形状是固定的：同一个接口，每次调用的 span 树长得差不多，所以 P99、错误率、吞吐这些聚合才有意义——你在对同一种东西求统计。Agent 的一次执行可能三步走完，也可能兜了二十七步，中间换了两次策略。对形状不同的东西求平均，得到的数字不指向任何具体的东西。", "所以“给 Agent 建一套监控大盘”这个说法，我觉得有点跑偏。大盘服务的是值班的人：五分钟内定位，止损，恢复。Agent 出的问题大多不需要五分钟内定位，它需要的是三天后有人坐下来，把上周所有失败的会话摊开，看出一个模式。这是两种不同的活动，只是碰巧共用一个名字。"], en: ["Traditional observability rests on an assumption: failure is decidable. A 500, a timeout, a stack trace, a queue backing up — no human judgment required, the machine already knows something broke. Alerting works because ‘wrong’ has a field you can align on.", "An agent has no such field. That wrong rebate number looks, from the system’s point of view, exactly like a correct answer. To know it was wrong you have to know which version of the rebate policy is in force, and that knowledge does not live in the trace. It lives in the business.", "The second problem is worse. A traditional trace has a fixed shape: the same endpoint produces roughly the same span tree every time, which is why P99, error rate, and throughput mean something — you are aggregating over one kind of thing. An agent run might finish in three steps or wander through twenty-seven, changing strategy twice along the way. Averaging over things with different shapes produces a number that points at nothing.", "Which is why ‘build a monitoring dashboard for the agent’ strikes me as slightly the wrong project. A dashboard serves the person on call: locate it in five minutes, stop the bleeding, restore. Most agent failures do not need to be located in five minutes. They need someone, three days later, to lay out every failed session from last week and see a pattern. Two different activities that happen to share a name."] },
    },
    {
      heading: { zh: "能复现的是输入，不是输出", en: "What you can reproduce is the input" },
      body: { zh: ["传统 debug 的第一步是复现。Agent 这一步直接没了。温度不为零，模型版本在厂商那边悄悄滚动，检索索引每天都在变，同样的输入喂进去也拿不到同样的输出。就算你把这些全锁死，得到的也只是测试环境里的一次巧合。", "一个很容易滑进去的替代方案，是记录模型自己的推理过程。CoT 读起来非常像解释：它说自己查了返利政策，找到了 12%。但那段文字是生成出来的，不是执行记录。模型完全可以把一件它没做过的事写得很像做过。我见过最难查的一类 bug 就长这样——推理写得头头是道，实际检索根本没命中，数字是顺着上下文编出来的。", "能被保证的不是复现输出，是复现输入。这次决策发生的时候，模型眼前到底有什么：system prompt 是哪一版，模板渲染进去的变量值是什么，检索命中的是哪几个文档的哪几个片段，工具描述是哪一版（改一个字模型的选择就会变，这件事被严重低估），上一轮的输出是怎么被截断的。", "这些加起来就是一次决策的证据。有证据，人可以自己判断模型为什么那么选。没有证据，你就是在让模型给自己作证。"], en: ["Debugging traditionally begins with reproduction. For agents that step is simply gone. Temperature is not zero, the vendor rolls model versions quietly, the retrieval index changes daily. Feed in the same input and you will not get the same output. Pin all of it down and what you have is one coincidence in a staging environment.", "The tempting substitute is to record the model’s own reasoning. Chain of thought reads like an explanation: it says it looked up the rebate policy and found 12%. But that text was generated, not logged. A model can describe something it never did, convincingly. The hardest bugs I have watched people chase look exactly like this — impeccable reasoning, a retrieval call that came back with nothing useful, and a number invented from context.", "What can be guaranteed is reproduction of the input. What was in front of the model at the moment it decided: which version of the system prompt, what values were rendered into the template, which chunks of which documents retrieval actually returned, which version of the tool description was in play — change one word in a tool description and the model’s choice changes, and this is badly underrated — and how the previous turn got truncated.", "Together those are the evidence for one decision. With the evidence, a person can work out why the model chose what it chose. Without it, you are asking the model to testify about itself."] },
    },
    {
      heading: { zh: "trace、log 和审计是三条流", en: "Traces, logs, and audit are three streams" },
      body: { zh: ["划分的标准可以压成一句话：trace 记的是决策链，log 记的是某一步内部的意外，审计记的是谁允许了什么。", "Agent trace 的最小单位是一次决策，不是一次 HTTP 请求。一次决策是这样一个三元组：模型当时看到了什么，它选了哪个工具、传了什么参数，拿回了什么。这三段必须落在同一个可查询的结构里，缺一段这条 trace 就不能用来解释行为。", "log 是另一回事：重试了三次、被限流、返回的 JSON 解析失败降级到了正则、连接池满了。这些是给工程师读的，不需要跨会话聚合，也不需要留很久。", "最常见的做法是把 prompt 全文和 response 全文 print 到 stdout，然后认为可观测性做完了。三个月后有人问“上个月所有调用了退款工具、金额超过一万的会话有哪些”，你只能 grep。这不叫可观测性，这叫把证据扔进了一个写完就不再读的地方。", "反过来的错误翻车更快：把 50k token 的 prompt 塞进 span attribute，先崩的是你的采集端。OTel 的规范自己就写了这条建议——生产环境把内容存在外部，span 里只放引用。这句话是被踩出来的，值得认真对待。", "第三条流最容易被漏掉。谁批准了这次写操作、这次工具调用带的是谁的身份、策略在哪一步拦了下来——这些东西长得像 trace，命运和 trace 毫无关系。trace 可以采样，审计不能采样；trace 存三十天够用，审计可能要存七年；trace 的访问控制和审计的访问控制是两套东西。混在一个后端里，最后是两边都做不好：要么审计记录被采样采没了，要么你在给全部 trace 付七年的存储费，只因为合规分不清它们。"], en: ["One line for the split: a trace records the chain of decisions, a log records what went sideways inside one step, and an audit record says who allowed what.", "The smallest unit of an agent trace is a decision, not an HTTP request. A decision is a triple: what the model saw, what it chose to call and with which arguments, what came back. Those three have to sit in one queryable structure. Lose any one of them and the trace can no longer explain behavior.", "Logs are a different job. Retried three times, got rate-limited, JSON parsing failed and fell back to a regex, connection pool exhausted. Engineers read these. They do not need to aggregate across sessions and they do not need to live long.", "The usual practice is to print the full prompt and the full response to stdout and consider observability done. Three months later someone asks which sessions last month called the refund tool for more than ten thousand, and the answer is grep. That is not observability. It is putting the evidence somewhere nobody will read it again.", "The opposite mistake breaks things faster: a 50k-token prompt stuffed into a span attribute will take down your collector before it takes down anything else. The OTel spec says so itself — in production, store content externally and keep a reference on the span. That sentence was earned.", "The third stream is the one that gets missed. Who approved this write, whose identity the tool call carried, where policy blocked it. These look like traces and have nothing in common with them. Traces can be sampled; audit cannot. Thirty days of traces is plenty; audit may need seven years. The access control on one is not the access control on the other. Put them in a single backend and you will do both badly — either the audit record got sampled away, or you are paying seven-year retention on every trace because compliance cannot tell them apart."] },
    },
    {
      heading: { zh: "怎么用 OpenTelemetry 落下来", en: "Doing it on OpenTelemetry" },
      body: { zh: ["说具体的。先搭骨架，属性是后面的事。一次用户会话用 gen_ai.conversation.id 串起来，跨多轮。每一轮里面："], en: ["Concretely, then. Build the skeleton first; attributes come later. A user session is stitched together by gen_ai.conversation.id across turns. Within a turn:"] },
      bullets: { zh: ["invoke_agent 是这一轮的根 span，Agent 的名字和版本挂在这里。", "每次模型推理是一个 chat span，span 名按约定是「操作名 + 模型名」，token 用量、finish reason、温度这些挂在它上面。", "每次工具调用是一个 execute_tool span，父节点是触发它的那次 chat。这条父子边就是「因为看到了 A，所以调了 B」这句话，它比两端的任何属性都重要。", "检索单独用 retrieval span，命中的文档 ID 和分数放这里，不要混进 chat 的属性里。", "子 Agent 就是嵌套的 invoke_agent，没有特别的。"], en: ["invoke_agent is the root span for the turn. Agent name and version belong here.", "Each model inference is a chat span, named by convention as operation plus model. Token usage, finish reason, and temperature hang off it.", "Each tool call is an execute_tool span whose parent is the chat span that triggered it. That parent-child edge is the sentence ‘because it saw A, it called B.’ It matters more than any attribute on either end.", "Retrieval gets its own retrieval span. Document IDs and scores go there, not into the chat span’s attributes.", "A subagent is a nested invoke_agent. Nothing special."] },
    },
    {
      heading: { zh: "骨架搭错了，属性补不回来", en: "Get the skeleton wrong and no attribute saves you" },
      body: { zh: ["这棵树的形状本身就是决策链。属性可以慢慢补，父子关系接错了就全废了——你会得到一堆时间上排得整齐、因果上完全断裂的 span。", "gen_ai.input.messages 和 gen_ai.output.messages 在约定里是 Opt-In 的，默认不采。这个默认值是对的，别急着打开。生产环境的姿势是内容进对象存储，span 里放一个引用键，读取走一层带审批的访问控制。", "还有一条很实际的坑：trace context 要能穿过 MCP 边界。工具调用经常跨进程、跨服务，如果 traceparent 没随着调用传下去，你的 trace 会在 Gateway 那里断成两截，后面全是孤儿 span。上一篇里我说 MCP Gateway 是身份传递的必经之路，这里补一句：它同样是 trace context 传递的必经之路。这两件事应该在同一个组件里一次做完，否则你会在两个地方各接一遍。", "最后，自定义属性不要往 gen_ai.* 里塞，用你自己的前缀。理由在下一节。"], en: ["The shape of that tree is the decision chain. Attributes can be backfilled; get the parent-child edges wrong and none of it is recoverable — you end up with spans that line up neatly in time and are causally disconnected.", "gen_ai.input.messages and gen_ai.output.messages are marked Opt-In in the conventions, off by default. That default is correct and there is no hurry to flip it. In production, content goes to object storage, the span holds a reference key, and reading it passes through access control.", "One practical trap: trace context has to survive the MCP boundary. Tool calls cross processes and services, and if traceparent does not travel with the call, your trace snaps in two at the gateway and everything past it becomes orphaned spans. I argued last time that an MCP gateway is the only place identity propagation can happen. It is also the only place trace context propagation can happen. Do both in one component, or you will implement propagation twice.", "Last one: do not put your own attributes under gen_ai.*. Use your own prefix. The reason is the next section."] },
    },
    {
      heading: { zh: "标准替你定义不了什么", en: "What the standard cannot define for you" },
      body: { zh: ["先说个不舒服的事实。这套约定一直在动：v1.27.0 把 prompt_tokens / completion_tokens 改成了 input_tokens / output_tokens；v1.37.0 把 gen_ai.system 改成 gen_ai.provider.name，同时把逐条消息的 event 换成了结构化的消息属性；2026 年 6 月整套 gen_ai 内容搬出主仓库，进了独立的 semantic-conventions-genai，主仓库在 v1.42.0 标记弃用、v1.43.0 移除。到今天为止，这套约定里没有任何一个 span、属性或指标是 Stable，全都还在 Development。", "有人会因此得出“再等等”的结论。", "我不同意。等的代价是这段时间的线上流量全部丢掉，而线上流量是你唯一能拿到真实分布的地方，丢了补不回来。", "该做的是分层：传输、上下文传播、SDK 用 OTel，这部分足够稳；语义自己定义一份内部模型，放在自己的命名空间下，采集的时候做一次映射。约定改了，你改的是映射层，不是你的数据。", "有三样东西，这套约定永远不会给你："], en: ["An uncomfortable fact first. These conventions keep moving. v1.27.0 renamed prompt_tokens and completion_tokens to input_tokens and output_tokens. v1.37.0 renamed gen_ai.system to gen_ai.provider.name and replaced per-message events with structured message attributes. In June 2026 the whole gen_ai surface moved out of the main semantic-conventions repository into a dedicated one, deprecated in v1.42.0 and removed in v1.43.0. As of today, not one GenAI span, attribute, or metric is marked Stable. All of it is still Development.", "Some people conclude they should wait.", "I don’t agree. Waiting costs you every session of production traffic in the meantime, and production traffic is the only place a real distribution exists. You cannot backfill it.", "Layer it instead. Transport, context propagation, and SDKs on OpenTelemetry — that part is solid enough. Semantics in your own internal model, under your own namespace, mapped once at ingest. When the convention changes you change a mapping, not your data.", "Three things the convention will never hand you:"] },
      bullets: { zh: ["任务成功与否。没有 gen_ai.task.success，也不该有——成功是业务定义的。退款 Agent 的成功是「金额对、且走了正确的审批路径」，客服 Agent 的成功是「用户没有再问第二遍」。", "身份。谁在问，这次工具调用以谁的身份执行。这是上一篇的主题，这里只补一点：trace 里没有身份，事后你连「这次越权是从哪一步进来的」都答不了。", "证据的版本。prompt 模板哪一版、工具描述哪一版、检索索引哪一天的快照。约定不关心这些，但没有它们你没法回放。"], en: ["Whether the task succeeded. There is no gen_ai.task.success and there should not be — success is a business definition. For a refund agent it is the right amount through the right approval path. For a support agent it is the user not asking again.", "Identity. Who asked, and under whose authority the tool call executed. That was the last essay’s subject; the addition here is that without identity on the trace you cannot even answer which step an over-permissioned call entered through.", "The version of the evidence. Which prompt template, which tool description, which day’s index snapshot. The convention does not care, and without it you cannot replay."] },
    },
    {
      heading: { zh: "手工编的五十条为什么一直是绿的", en: "Why the hand-written fifty always pass" },
      body: { zh: ["上一篇我写过，AgentOps 有一半守不住，trace 采集和回放会被平台内置。我现在还是这么看，而上面那三样正好是它的另一半：采集会被内置，因为它锚在模型能力上；这三样内置不了，因为它们锚在你的业务定义、你的身份体系、你的版本管理上。自研 trace SDK 是浪费，自研这三样不是。", "接着往下走一层。可观测性最后要交付给谁？", "几乎每个 Agent 团队都有一个 eval 集，五十到两百条，人手写的，跑起来一片绿，线上照样出事。问题不在题目质量，在分布。人编题的时候编的是自己想得到的情况，而线上出事的永远是想不到的那些：用户把两个问题写在一句话里、传上来一张扫描件、公司悄悄改了个内部术语、上游 API 多返回了一个字段。这些你编不出来，因为编得出来就已经处理了。", "真实分布只有一个地方拿得到，就是线上 trace。手写的那五十条真正的用处是回归，防止你把修好的东西改坏。它不承担发现新问题的职责，但大部分团队正是这么用它的。", "trace 唯一缺的是标签。标注贵，点赞按钮几乎没人点，LLM-as-judge 便宜但恰好在关键 case 上不可靠。", "有一个信号被严重低估：人工接管，尤其是“人改了什么”。Agent 起草了一封邮件，用户发出去之前删掉了金额那一行；Agent 填好一张工单，用户提交前换了分类。这不需要任何标注成本，用户已经免费告诉你正确答案了。想拿到它，前提是你的产品把 Agent 的输出和用户最终提交的东西都存下来，并且能 diff。这是个产品设计决定，不是可观测性的技术决定，但它决定了你的负样本是靠买还是白捡。"], en: ["Last time I wrote that half of AgentOps cannot be defended, that trace collection and replay will be absorbed into the platforms. I still think so, and those three things are the other half of that sentence. Collection gets absorbed because it is anchored to model capability. These cannot be, because they are anchored to your business definitions, your identity system, your version control. Building your own trace SDK is a waste. Building these three is not.", "Which raises the next question. Who is all this telemetry finally delivered to?", "Nearly every agent team has an eval set — fifty to two hundred cases, written by hand, all green, and production breaks anyway. The problem is not case quality. It is distribution. People write the situations they can imagine, and production fails on the ones they cannot: two questions in one sentence, a scanned image instead of text, an internal term the company quietly renamed, an upstream API that started returning an extra field. You cannot write those cases, because if you could imagine them you would have handled them.", "A real distribution lives in exactly one place: production traces. The hand-written fifty are a regression suite — they keep you from re-breaking what you already fixed. They are not an instrument for finding new problems, though that is exactly how most teams use them.", "What traces lack is labels. Annotation is expensive, thumbs-up buttons go unclicked, and LLM-as-judge is cheap but unreliable precisely on the cases that matter.", "One signal is badly underrated: human takeover, and specifically what the human changed. The agent drafts an email and the user deletes the line with the number before sending. The agent fills a ticket and the user changes the category before submitting. That costs nothing to collect, and the user has already told you the correct answer for free. Getting it requires your product to record both the agent’s output and what the human finally submitted, and to diff them. That is a product decision, not an observability decision — and it decides whether your negative examples are bought or found."] },
    },
    {
      heading: { zh: "回流管道", en: "The return path" },
      body: { zh: ["从 trace 到 eval 的那段路，硬要求只有一个：可重放。", "你要能把上周那次失败的输入，喂给这周的新 prompt，看它是不是修好了。这件事的前提回到第二节：你存的必须是输入证据，不是渲染后的结果。只存了最终那串 prompt 文本的话，模板一改这条 case 就废了，它里面写死了旧模板的结构。模板版本、变量值、检索命中的文档 ID 分开存，你才能用新模板重新渲染一遍。", "检索这一层还有额外的麻烦：索引会变。上周命中的文档这周可能已经被更新或删除。要么给索引做快照，要么至少记下文档版本号，接受一部分 case 会随时间失效。这件事我没见过干净的解法，见到的都是各自能接受的妥协。", "管道本身不复杂：按规则从线上挑 trace（人工接管过的、被策略拦过的、耗时异常的、成本异常的），补标签，进 case 库，晋级到回归集。难的是让它一直活着。这种管道没人催，坏了不会告警，通常在建好之后的第一个季度就悄悄停了。"], en: ["Between a trace and an eval case there is exactly one hard requirement: replay.", "You need to feed last week’s failing input into this week’s prompt and see whether it is fixed. Which brings back the second section: what you stored has to be the input evidence, not the rendered result. Store only the final prompt string and the case dies the moment you change the template — it has the old template’s structure baked into it. Store the template version, the variable values, and the retrieved document IDs separately and you can render it again.", "Retrieval adds its own mess. The index moves. A document retrieved last week may have been updated or deleted since. Snapshot the index, or at least record document versions and accept that some cases expire. I have not seen a clean solution to this, only compromises people can live with.", "The pipeline itself is not complicated: select traces by rule (a human took over, policy blocked it, latency was strange, cost was strange), attach labels, push into a case library, promote into the regression set. The hard part is keeping it alive. Nobody chases this pipeline, nothing pages when it stops, and it usually goes quiet within a quarter of being built."] },
    },
  ],
  closing: { zh: "判断一个团队有没有真的在做可观测性，我用一个问题：上周失败的会话里，多少是检索没召回，多少是工具参数给错，多少是模型看到了正确的东西但选错了工具？答不出来，说明你存下来的东西只够证明系统在运行，不够解释它做过什么。有多少块仪表盘都一样。", en: "Here is the question I use to tell whether a team is actually doing this. Of last week’s failed sessions, how many were retrieval missing the document, how many were wrong tool arguments, and how many were the model seeing the right thing and picking the wrong tool? If nobody can answer, what you stored is enough to prove the system was running and not enough to explain what it did. The number of dashboards does not change that." },
} satisfies ArticleBody;

const articles: Record<string, ArticleBody | undefined> = { "agent-infra": agentInfra, "agent-observability": agentObservability };

function App() {
  const [dark, setDark] = useState(false);
  const [lang, setLang] = useState<Language>("zh");
  const [query, setQuery] = useState("");
  const [activeTag, setActiveTag] = useState("全部");
  const [page, setPage] = useState<"home" | "article" | "about">("home");
  const [activeId, setActiveId] = useState(featured.id);
  const [progress, setProgress] = useState(0);
  const t = copy[lang];

  useEffect(() => { const savedTheme = window.localStorage.getItem("shihao-theme"); setDark(savedTheme === "dark"); const savedLang = window.localStorage.getItem("shihao-language"); if (savedLang === "en" || savedLang === "zh") setLang(savedLang); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; window.localStorage.setItem("shihao-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { window.localStorage.setItem("shihao-language", lang); }, [lang]);
  useEffect(() => {
    if (page !== "article") return;
    const updateProgress = () => {
      const available = document.documentElement.scrollHeight - window.innerHeight;
      setProgress(available > 0 ? Math.min(100, (window.scrollY / available) * 100) : 0);
    };
    updateProgress();
    window.addEventListener("scroll", updateProgress, { passive: true });
    return () => window.removeEventListener("scroll", updateProgress);
  }, [page]);

  const tags = [t.all, ...Array.from(new Set(posts.map((post) => post.tag[lang])))];
  const filtered = useMemo(() => posts.filter((post) => (activeTag === t.all || post.tag[lang] === activeTag) && `${post.title[lang]}${post.excerpt[lang]}`.toLowerCase().includes(query.toLowerCase())), [activeTag, lang, query, t.all]);
  const showPage = (next: "home" | "article" | "about") => { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openPost = (id: string) => { setActiveId(id); showPage("article"); };
  const activePost = posts.find((post) => post.id === activeId) ?? featured;
  const activeArticle = articles[activePost.id];
  const changeLanguage = () => { setLang(lang === "zh" ? "en" : "zh"); setActiveTag(lang === "zh" ? "All" : "全部"); };
  const navToWriting = () => {
    if (page !== "home") {
      setPage("home");
      window.setTimeout(() => document.querySelector("#writing")?.scrollIntoView({ behavior: "smooth" }), 0);
    }
  };

  const Header = () => <header className="wrap"><nav className="nav site-nav" aria-label="Main navigation">
    <button className="nav-brand" onClick={() => showPage("home")}>Shihao Xiong</button>
    <button className={page === "home" ? "nav-link active" : "nav-link"} onClick={navToWriting}>{t.articles}</button>
    <button className={page === "about" ? "nav-link active" : "nav-link"} onClick={() => showPage("about")}>{t.about}</button>
    <button className="nav-link language" onClick={changeLanguage}>{lang === "zh" ? "EN" : "中文"}</button>
    <button className="btn btn-secondary theme-btn" onClick={() => setDark((value) => !value)} aria-label="Toggle color theme">{dark ? "☾ 夜" : "☀ 日"}</button>
  </nav></header>;

  const Timeline = () => <section className="timeline stack" aria-label="Timeline">
    <h6 className="section-label">{lang === "zh" ? "正在思考 / Now" : "Currently thinking"}</h6>
    <div className="tl-row"><div className="tl-rail"><i /><u /></div><div className="card tl-card"><small>NOW</small><h4>{lang === "zh" ? "Agent Infra 与企业运行边界" : "Agent infrastructure and enterprise boundaries"}</h4><p>{lang === "zh" ? "持续记录 Agent 如何安全、稳定、可治理地完成真实工作。" : "Notes on helping agents complete real work safely, reliably, and governably."}</p></div></div>
    <div className="tl-row"><div className="tl-rail"><i className="olive" /><u /></div><div className="card tl-card"><small>WRITING</small><h4>{lang === "zh" ? "把尚未成形的思考写清楚" : "Making half-formed thoughts clear"}</h4><p>{lang === "zh" ? "技术笔记与工作方法，慢慢整理，持续更新。" : "Technical notes and ways of working, gathered gradually."}</p></div></div>
  </section>;

  const Footer = () => <footer className="wrap site-footer"><span>© 2026 Shihao Xiong</span><span>{lang === "zh" ? "慢慢写，也认真写。" : "Written slowly, with care."}</span><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>{t.top}</button></footer>;

  const Home = () => <main className="wrap stack home-page">
    <section className="hero" id="top"><div className="hero-copy"><h6>SHIHAO XIONG · FIELD NOTES</h6><h1>{lang === "zh" ? "构建 Agent 基础设施，也把过程写下来。" : "Building agent infrastructure, and writing it down."}</h1><p>{lang === "zh" ? "关于企业 Agent、工程实践与慢慢形成的想法。这里记录问题如何被拆开、验证，最后变成可靠的系统。" : "Notes on enterprise agents, engineering practice, and ideas taking shape—how problems are unpacked, tested, and turned into reliable systems."}</p><div className="hero-actions"><a className="btn btn-primary" href="#writing">{lang === "zh" ? "阅读文章" : "Read notes"}</a><button className="btn btn-secondary" onClick={() => showPage("about")}>{t.about}</button></div></div><div className="portrait-ring"><img className="portrait washed" src="/images/shihao-sunset.png" alt={lang === "zh" ? "日落海面" : "Sunset over the sea"} /></div></section>
    <section className="now-bar" aria-label="Now"><h6>{lang === "zh" ? "现在" : "Now"}</h6><div className="now-item"><span className="dot" /><div><b>{lang === "zh" ? "整理 Agent Infra 的实践" : "Mapping agent infrastructure"}</b><span>{lang === "zh" ? "写作 · 进行中" : "Writing · in progress"}</span></div></div><div className="now-item"><span className="dot dot-2" /><div><b>{lang === "zh" ? "阅读与构建" : "Reading and building"}</b><span>{lang === "zh" ? "工程 · 持续进行" : "Engineering · ongoing"}</span></div></div><div className="now-item"><span className="dot dot-idle" /><div><b>{lang === "zh" ? "更新这个小站" : "Tending this small site"}</b><span>{lang === "zh" ? "博客 · 缓慢更新" : "Blog · slowly updated"}</span></div></div></section>
    <article className="card elev-sm featured"><span className="card-kicker">{lang === "zh" ? "最新一篇" : "Latest note"} · {featured.date} · {featured.minutes}</span><h2>{featured.title[lang]}</h2><p>{featured.excerpt[lang]}</p><button className="btn btn-primary" onClick={() => openPost(featured.id)}>{lang === "zh" ? "继续读 →" : "Continue reading →"}</button></article>
    <section className="cols" id="writing"><div className="col"><div className="row-between"><h6>{lang === "zh" ? "技术笔记" : "Technical notes"}</h6><span className="quiet-count">{posts.length} {lang === "zh" ? "篇" : "note"}</span></div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} aria-label={t.search} /></label><div className="filters" aria-label="Article tags">{tags.map((tag) => <button className={activeTag === tag ? "active" : ""} key={tag} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div><div className="note-list">{filtered.map((post) => <button className="note" key={post.id} onClick={() => openPost(post.id)}><span className="dot" /><span><h4>{post.title[lang]}</h4><small>{post.date} · {post.minutes}</small></span></button>)}{filtered.length === 0 && <p className="empty">{t.noResults}</p>}</div></div><div className="col"><div className="row-between"><h6 className="olive-label">{lang === "zh" ? "写作方向" : "Writing directions"}</h6></div><div className="card career-card"><h4>{lang === "zh" ? "让系统在企业里长期工作" : "Making systems work over time"}</h4><small>{lang === "zh" ? "Agent Infra · 安全与治理" : "Agent infra · safety and governance"}</small></div><div className="card career-card"><h4>{lang === "zh" ? "把复杂的工程问题说明白" : "Explaining complex engineering"}</h4><small>{lang === "zh" ? "工作方法 · 技术笔记" : "Ways of working · technical notes"}</small></div><div className="card career-card"><h4>{lang === "zh" ? "持续学习，持续校正" : "Learn, then recalibrate"}</h4><small>{lang === "zh" ? "阅读 · 观察 · 实践" : "Reading · observation · practice"}</small></div></div></section>
    <Timeline />
    <section className="band"><div><h4>{lang === "zh" ? "想聊聊，或者订阅更新" : "Say hello or follow along"}</h4><p>{lang === "zh" ? "有想法、问题或一起在做的事，欢迎来信。" : "Ideas, questions, or work in progress are always welcome."}</p></div><div className="band-actions"><a className="btn btn-primary" href="mailto:xiongshihao97@gmail.com">Email</a><button className="btn btn-secondary" onClick={() => showPage("about")}>{t.about}</button></div></section>
  </main>;

  const About = () => <main className="wrap"><div className="about-page"><aside className="about-side"><img className="portrait-lg washed" src="/images/shihao-sunset.png" alt={lang === "zh" ? "日落海面" : "Sunset over the sea"} /><a className="btn btn-secondary btn-block" href="mailto:xiongshihao97@gmail.com">Email <span>↗</span></a><button className="btn btn-secondary btn-block" onClick={() => showPage("home")}>{t.articles} <span>→</span></button></aside><div className="about-body"><section><h6>{lang === "zh" ? "关于 / About" : "About"}</h6><h1>{lang === "zh" ? "你好，我是 Shihao。" : "Hi, I’m Shihao."}</h1><p>{t.aboutLead}</p><p>{t.aboutBody}</p></section><Timeline /><section><h6 className="section-label">{lang === "zh" ? "关注" : "Focus"}</h6><div className="tag-row"><span className="tag tag-outline">Agent Infra</span><span className="tag tag-outline">Systems</span><span className="tag tag-outline">AgentOps</span><span className="tag tag-outline">Writing</span><span className="tag tag-outline">AI</span></div></section><section className="cta"><h4>{lang === "zh" ? "聊聊？" : "Let’s talk."}</h4><p>{lang === "zh" ? "关于基础设施、团队，或者一个尚未想清楚的工程问题，都欢迎写信。" : "Infrastructure, teams, or an engineering problem that is not clear yet—all welcome."}</p><a className="btn btn-primary" href="mailto:xiongshihao97@gmail.com">{lang === "zh" ? "写信给我" : "Email me"}</a></section></div></div></main>;

  const Article = () => {
    if (!activeArticle) return <main className="wrap"><div className="article"><article className="prose"><span className="tag tag-accent">{activePost.tag[lang]}</span><h1>{activePost.title[lang]}</h1><p className="lead">{t.comingSoon}</p><button className="btn btn-secondary back-button" onClick={() => showPage("home")}>← {t.back}</button></article></div></main>;
    return <><div className="progress-track"><div className="progress-bar" style={{ width: `${progress}%` }} /></div><main className="wrap"><div className="article"><aside className="aside"><button className="btn btn-secondary back-button" onClick={() => showPage("home")}>← {t.back}</button><nav className="card toc" aria-label="Table of contents"><span className="card-kicker">{lang === "zh" ? "目录" : "Contents"}</span>{activeArticle.sections.map((section, index) => <a href={`#section-${index + 1}`} key={section.heading.zh}><i>{String(index + 1).padStart(2, "0")}</i><span>{section.heading[lang]}</span></a>)}</nav><div className="card author-card"><div className="author-head"><img className="washed" src="/images/shihao-sunset.png" alt="" /><div><b>Shihao Xiong</b><span>Agent Infrastructure</span></div></div><small>{activePost.date} · {activePost.minutes}</small></div></aside><article className="prose"><span className="tag tag-accent">{activePost.tag[lang]}</span><h1>{activePost.title[lang]}</h1><p className="dek">{activeArticle.subtitle[lang]}</p><p className="lead">{activeArticle.intro[lang]}</p>{activeArticle.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading.zh}><div className="h-num"><i>{String(index + 1).padStart(2, "0")}</i><h3>{section.heading[lang]}</h3></div>{section.body[lang].map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets[lang].map((item) => <li key={item}>{item}</li>)}</ul>}{section.figure && <figure><img src={section.figure.src} alt={section.figure.caption[lang]} /><figcaption>{section.figure.caption[lang]}</figcaption></figure>}</section>)}<p className="closing">{activeArticle.closing[lang]}</p>{activePost.topics.length > 0 && <div className="tag-row">{activePost.topics.map((topic) => <span className="tag tag-outline" key={topic}>{topic}</span>)}</div>}</article></div></main></>;
  };

  return <div className="site-shell"><Header />{page === "home" ? <Home /> : page === "about" ? <About /> : <Article />}<Footer /></div>;
}

createRoot(document.getElementById("root")!).render(<App />);
