import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

type Language = "zh" | "en";
type Localized = Record<Language, string>;
type Post = { id: string; date: string; title: Localized; excerpt: Localized; tag: Localized; minutes: string; featured?: boolean; published?: boolean };
type ArticleBody = { subtitle: Localized; intro: Localized; sections: { heading: Localized; body: Record<Language, string[]>; bullets?: Record<Language, string[]>; figure?: { src: string; caption: Localized } }[]; closing: Localized };

const posts: Post[] = [
  {
    id: "agent-infra",
    date: "2026.07.28",
    title: { zh: "为什么 Agent Infra 越来越重要", en: "Why Agent Infra Matters More Than Ever" },
    excerpt: { zh: "主循环现在可以买到了。真正的分水岭，是你第一次让 Agent 写生产数据那天。", en: "The main loop is something you buy now. The dividing line is the day you first let an agent write production data." },
    tag: { zh: "Agent Infra", en: "Agent Infra" },
    minutes: "7 min",
    featured: true,
    published: true,
  },
];

const featured = posts.find((post) => post.featured)!;

const copy = {
  zh: { articles: "文章", about: "关于", search: "搜索文章", all: "全部", latest: "最新文章", selected: "精选文章", read: "阅读文章", comingSoon: "即将上线", back: "返回文章列表", contact: "和我聊聊", top: "回到顶部 ↑", aboutLead: "你好，我是 Shihao，一个 INFJ。习惯先把世界安静地看一会儿，再决定留下些什么。", aboutBody: "我相信细微的感受值得被认真对待，也愿意把那些尚未成形的思考，慢慢整理成清晰的文字。", noResults: "没有找到匹配的文章。", essay: "文章" },
  en: { articles: "Writing", about: "About", search: "Search writing", all: "All", latest: "Latest writing", selected: "Selected writing", read: "Read essay", comingSoon: "Coming soon", back: "Back to writing", contact: "Say hello", top: "Back to top ↑", aboutLead: "Hi, I’m Shihao, an INFJ. I tend to sit quietly with the world for a while before deciding what to leave behind.", aboutBody: "I believe subtle feelings deserve attention, and I like turning half-formed thoughts into words with a little more clarity.", noResults: "No matching essays yet.", essay: "Essay" },
} satisfies Record<Language, Record<string, string>>;

const agentInfra = {
  subtitle: { zh: "难度不会消失，它只是换了个地方。", en: "Difficulty doesn’t disappear. It moves." },
  intro: { zh: "一个企业 Agent 最常见的死法，不是答错问题，是答对了一个不该由它回答的问题。而这件事和模型聪不聪明没有任何关系。", en: "The most common way an enterprise agent fails is not by getting the answer wrong. It gets the answer right, for someone who should never have received it. Nothing about that failure has to do with how smart the model is." },
  sections: [
    {
      heading: { zh: "现在死掉的不是模型", en: "What fails now isn’t the model" },
      body: { zh: ["具体是这样：Agent 通过一个服务账号接进了 CRM。为了让它什么都查得到，这个账号的权限被开成了所有用户的并集。于是一个普通销售问它，我们给某个客户的折扣底价是多少，它准确地、带着引用地回答了。模型没出错，检索也没出错。错在这套系统从头到尾不知道提问的人是谁。", "2024 年不会有人讨论这种问题。那时候争的是循环本身能不能收敛：ReAct 会不会原地打转，上下文塞到第几轮开始崩，工具调用能不能稳定吐出合法参数。一个能连续跑十五步不散架的 Agent，本身就算成果。", "这部分现在是买来的。DeepAgents 把规划、文件系统、上下文卸载、子 Agent、Skills 和人工审批打成了一个 Harness；Claude Agent SDK 给你另一套；OpenCode 这类客户端 Agent 连代码仓库的上下文管理都替你想好了。你准备自己写的那个主循环，大概率已经有人写得比你好，而且开源了。", "所以现在停下来的项目，很少是因为模型不够聪明。它们卡在权限，卡在凭据，卡在没人能说清上周三那次错误的写操作是从哪一步来的。"], en: ["Here is the shape of it. An agent is wired into a CRM through a service account. To make sure it can look anything up, that account is given the union of every user’s permissions. A salesperson asks what floor price we gave a particular customer, and the agent answers — accurately, with a citation. The model did not fail. Retrieval did not fail. The system simply never knew who was asking.", "In 2024 nobody would have been discussing that. The argument then was whether the loop converged at all: whether ReAct would spin in place, how many turns before the context fell apart, whether tool calls would reliably emit valid arguments. An agent that ran fifteen steps without coming apart was itself the result.", "That part is now something you buy. DeepAgents packages planning, a file system, context offloading, subagents, skills, and human approval into one harness. Claude Agent SDK gives you another. Client agents like OpenCode have already worked out repository context for you. Whatever main loop you were going to write, someone has probably written a better one and open-sourced it.", "So projects rarely stall now because the model wasn’t clever enough. They stall on permissions, on credentials, on nobody being able to explain which step caused last Wednesday’s bad write."] },
    },
    {
      heading: { zh: "难度守恒", en: "Difficulty is conserved" },
      body: { zh: ["“价值转移到基础设施层”这句话很容易说得像句空话，因为它跳过了原因。", "区别在于两种复杂性。第一种可以在一个仓库里被完整表达出来。Agent 主循环就是这样：说到底是几千行状态机加一组 prompt，边界清楚，跟你在哪家公司无关。这类问题有个特点，只要有人把它写对过一次，就可以被抄一万次。开源特别擅长收敛这种东西，而且只会越来越快。", "第二种没法这么处理。把身份联邦打进一个跑了十五年、当年开发者已经离职的 ERP。让检索层正确继承 SharePoint 里攒了二十年的目录权限。说服安全团队签字，同意一个进程能往生产库写数据。这些工作量不会因为别人做过而减少，因为你面对的不是同一个 ERP，也不是同一个安全团队。", "我倾向于这么区分：Runtime 的难度是智力密度高，Infra 的难度是协商成本高。智力密度可以被一次性攻克，然后免费复制；协商成本每个客户都要重付一遍。开源能替你省掉前者，碰不到后者。", "基础设施并不是突然变得更值钱了。是难度守恒。上面那层被压平以后，下面的部分露出来了。"], en: ["Saying that value moves to the infrastructure layer is easy and usually empty, because it skips the reason.", "There are two kinds of difficulty. The first can be fully expressed inside one repository. The agent loop is like that: a few thousand lines of state machine plus a set of prompts, clear boundaries, no dependence on which company you work at. Solve it correctly once and it can be copied ten thousand times. Open source is extremely good at collapsing this kind of problem, and getting faster at it.", "The second kind resists that. Federating identity into an ERP that has run for fifteen years, whose original developers left. Making retrieval inherit twenty years of accumulated folder permissions in SharePoint. Getting a security team to sign off on a process that can write to a production database. None of this gets smaller because someone else did it, because you are not facing the same ERP or the same security team.", "The distinction I find useful: runtime difficulty is dense in intelligence, infrastructure difficulty is dense in negotiation. Intelligence can be solved once and then copied for free. Negotiation is paid again at every customer. Open source spares you the first and cannot touch the second.", "Infrastructure did not suddenly become more valuable. Difficulty is conserved. The upper layer flattened, and what was underneath became visible."] },
      figure: { src: "/images/agent-architecture-components.png", caption: { zh: "这张图通常被当成组件清单来读。也可以换个读法：Runtime 那一格正在被开源压平，剩下的格子是难度沉降下去的地方。", en: "This diagram usually gets read as a component checklist. Another reading: the runtime box is being flattened by open source, and the remaining boxes are where the difficulty settled." } },
    },
    {
      heading: { zh: "状态所有权在往上走", en: "State ownership keeps moving up" },
      body: { zh: ["客户端 Agent、服务端 Agent、Agent PaaS，这种分法把两件事混在了一起：跑在哪，和怎么卖。", "有一个问题比它们都管用：Session 在谁手里，出事谁背。", "按这个问，是三类。第一类，状态在你自己的目录里，隔离靠操作系统的用户权限，出事你自己收拾，Codex、Claude Code、IDE 里那些 Agent 都算。第二类，企业的技术团队把 Runtime 接进自己的应用，自己实现 SessionStore，自己给 Sandbox 挂工作区，出事这个团队背。第三类，平台统一管 Agent、Environment、Session、权限和调度，出事平台背。", "要紧的不是这三类怎么排序，而是从第一类走到第三类，并不是封装越来越厚，是责任在往上转移。", "举个具体的。你自己用 Claude Code 的时候，要不要让它执行这条 rm，是你当场做的一个判断，判断错了你自己扛。同样这件事放到一个跑着一百个 Agent 的平台上，它必须变成一条可配置、可审计、可回滚的策略，因为不可能让一百个人各自当场判断，也不可能出了事没人能还原过程。", "一个原本属于个人的判断，被迫变成了一个必须被产品化的东西。这就是基础设施出现的位置。", "市场确实在往第三类走，但不是因为第三类更先进，而是因为企业买不了“每个员工自己判断”。这么看，基础设施重不重要就不太算一个观点了，它更像是状态所有权上移之后的一个推论。"], en: ["Client agent, server agent, agent PaaS — that split conflates where something runs with how it is sold.", "One question does more work: who holds the session, and who is liable when it goes wrong.", "By that test there are three kinds. In the first, state lives in your own directory, isolation comes from your OS user account, and you absorb the consequences yourself: Codex, Claude Code, the agents inside your IDE. In the second, an enterprise team wires a runtime into their own application, implements its session store, mounts a workspace for its sandbox, and carries the liability. In the third, a platform governs agents, environments, sessions, permissions, and scheduling, and the platform carries it.", "What matters is not the ordering. It is that moving from the first to the third is not thicker packaging. Responsibility is being transferred upward.", "Concretely: when you run Claude Code yourself, whether to let it execute a particular rm is a judgment you make on the spot, and you clean up your own mistake. Put the same question on a platform running a hundred agents and it has to become a policy that can be configured, audited, and rolled back — because a hundred people cannot each judge on the spot, and nobody can be left unable to reconstruct what happened.", "A judgment that belonged to a person is forced to become a product. That is the position infrastructure occupies.", "The market is moving toward the third kind, not because it is more advanced, but because enterprises cannot buy ‘every employee decides for themselves.’ Whether infrastructure matters is therefore less an opinion than a consequence of state ownership moving up."] },
    },
    {
      heading: { zh: "L3 是一道台阶", en: "L3 is a step, not a slope" },
      body: { zh: ["上面说的是方向。但“越来越重要”是个关于时间的说法，得说清到底是什么在变。企业 Agent 按“能干什么”分四级就够用了：只读问答、生成草稿和分析、审批后执行写操作、在策略边界内自动执行。", "台阶在 L3。Agent 第一次能改变世界的状态，于是两个问题变成硬性的：这次写操作是以谁的身份做的？如果它写错了，谁能在事后精确指出是哪一步、哪个参数？", "答不上来，L3 就上不了线。不是效果不好，是合规不让。MCP Gateway 在 L2 以前是个可选项，跨过 L3 它是开关。", "基础设施投入的那条曲线，在 L3 之前接近平的，跨过 L3 陡然抬起来。", "而需求正在过这道台阶。原因很俗：L1 的 ROI 已经被验证完，也被榨干了。知识问答省的是查资料的十分钟，真正的钱在“少雇一个人做对账”。要去拿那笔钱，Agent 必须能写数据。", "这才是“越来越”的机制。不是基础设施自己在变重要，是需求在往台阶另一边走。四级各自要什么，大致是这样："], en: ["That is a claim about direction. But ‘more than ever’ is a claim about time, and it has to say what actually changed. Four levels are enough to grade an enterprise agent by what it is allowed to do: read-only Q&A, drafts and analysis, writes after approval, autonomous execution inside a policy.", "The step is at L3. For the first time the agent can change the state of the world, which makes two questions mandatory. Under whose identity was this write performed? If it wrote the wrong thing, who can point to the exact step and the exact argument afterward?", "Without answers, L3 does not ship. Not because quality is poor — because compliance says no. An MCP gateway is optional up to L2. Past L3 it is the switch.", "The infrastructure investment curve is nearly flat below L3 and turns sharply upward across it.", "And demand is crossing over. The reason is mundane: L1’s ROI has been proven and also exhausted. Knowledge lookup saves ten minutes of searching. The real money is in not hiring another person to do reconciliation, and to reach it the agent has to write data.", "That is the mechanism behind ‘more than ever.’ Infrastructure is not becoming more important on its own. Demand is walking across the step. Roughly what each level needs:"] },
      bullets: { zh: ["L1，只读问答：一个知识库加一层权限过滤就够了。这时候去建 Sandbox 和 Memory 平台是纯粹的跑偏。", "L2，草稿与分析：开始需要引用和可追溯，因为草稿会被人当成事实用掉。", "L3，审批后执行写操作：台阶在这里。身份传递和证据链从功能变成上线许可。", "L4，在策略边界内自动执行：审批已经不在环上，所有约束必须提前沉到策略里，出事之后只有日志能替你说话。"], en: ["L1, read-only Q&A: a knowledge base and a permission filter are enough. Building a sandbox or a memory platform here is a straight detour.", "L2, drafts and analysis: citations and traceability start to matter, because drafts get used as fact.", "L3, writes after approval: this is the step. Identity propagation and an evidence chain stop being features and become permission to launch.", "L4, autonomous execution inside a policy: approval has left the loop, so every constraint has to be pushed down into the policy in advance, and afterward only the logs can speak for you."] },
    },
    {
      heading: { zh: "五块里只有两块真的属于你", en: "Only two of the five are really yours" },
      body: { zh: ["通常说的 Agent Infra 是五块东西：Sandbox、MCP Gateway、企业知识平台、Memory、AgentOps。这里应该接一个反驳。", "“底层标准化了，所以基础设施层有机会”，这个故事每一波技术浪潮都出现过，而那些故事大部分输给了平台方直接把功能内置。这次的证据也不弱：代码执行、MCP、memory、connector，模型厂商都在自己出，出得还很快。", "这个反驳是对的。但它不是均匀地对。", "分辨的标准是，这个能力锚在谁的资产上。", "锚在模型能力上的会被吃掉。一个能跑 Python 的隔离容器，一个把历史对话按相关性塞回去的 memory 层，这两件事模型厂商比你更该做，也更容易做好。我不看好它们独立成产品。", "锚在客户自己的身份体系和数据边界上的吃不掉。MCP Gateway 要接的是客户的 IdP、客户的 OAuth 配置、客户那套写在表格里的字段级授权规则；企业知识平台要继承的是客户 SharePoint 和几个库里攒了二十年的 ACL。没有哪个模型厂商会去接一万家公司的 AD。", "AgentOps 在中间。Trace 和回放会被平台内置，这部分守不住。但“这次任务有没有真的完成业务目标”必须接客户自己的指标，那部分内置不了。", "回到开头那个折扣底价。它需要的不是把 API 转成 MCP，是身份传递：Agent 调 CRM 的时候带的必须是提问那个销售的身份，而不是一个万能服务账号。这一条就够解释为什么 Gateway 不能是个适配层。", "所以优先级不是五块都做。先做 Gateway 和知识平台，剩下三块能买就买。"], en: ["Agent infra usually means five things: sandbox, MCP gateway, enterprise knowledge, memory, AgentOps. This is where an objection belongs.", "‘The lower layer standardizes, so there is an opening in infrastructure’ is a story every technology wave has produced, and most of those stories lost to the platform vendor shipping the feature itself. The evidence this time is not weak. Code execution, MCP, memory, connectors — model vendors are building all of it, quickly.", "The objection is right. It is not evenly right.", "The test is what a capability is anchored to.", "Anchored to model capability, it gets absorbed. An isolated container that runs Python; a memory layer that ranks past turns and pushes them back in. Model vendors should build those and will build them better. I do not expect either to survive as a standalone product.", "Anchored to the customer’s own identity system and data boundary, it cannot be absorbed. An MCP gateway has to reach their IdP, their OAuth configuration, their field-level authorization rules that live in a spreadsheet. An enterprise knowledge platform has to inherit twenty years of ACLs across their SharePoint and their databases. No model vendor is going to integrate ten thousand companies’ Active Directory.", "AgentOps sits in between. Traces and replay will be built into the platforms and cannot be defended. Whether the task actually achieved a business outcome has to attach to the customer’s own metrics, and that part cannot be.", "Back to the floor price. What that failure needed was not an API-to-MCP adapter. It needed identity propagation: when the agent calls the CRM it must carry the identity of the salesperson who asked, not a service account that can see everything. That one requirement is enough to explain why a gateway cannot be a translation layer.", "So the priority is not all five. Build the gateway and the knowledge platform. Buy the rest if you can."] },
    },
    {
      heading: { zh: "审计是自动化的前提", en: "Auditing comes before automation" },
      body: { zh: ["前面全在讲加约束。代价得放在这里，不然不诚实。", "每一道约束都在收窄 Agent 的可行动空间，也在拉长时延。审批门是这类产品最容易翻车的地方：一个三十秒能做完的任务，加一道人工审批，变成四小时，因为审批的人在开会。ROI 就这么蒸发了。你没省下人力，你只是把“做”换成了“审”，而审的人还得先读懂 Agent 干了什么，这经常比自己动手更慢。", "结论不是“要平衡”。具体一点：审批要按风险分级，不能按动作类型分级。“所有写操作都要审批”是最省心也最致命的一条策略。退五块钱和退五万块钱不该走同一条路，改一个联系人手机号和改一个信用额度也不该。", "还有一个反直觉的地方。可观测性做得好，才有资格少审批。你能在事后精确查出每一步、每个参数、每一次授权是怎么来的，你就敢让更多东西自动跑。审计不是自动化的负担，是它的前提。", "顺着这个，我不太同意把 AgentOps 排在优先级第三位。它该和 Gateway 一起做。不是为了好看的仪表盘，是因为不先把证据链铺好，后面每一次“要不要再放开一点”的讨论都只能靠拍脑袋。"], en: ["Everything above argues for adding constraints. The cost belongs here, or the argument is dishonest.", "Every constraint narrows what the agent can do and lengthens how long it takes. Approval gates are the most common way these products die. A task that takes thirty seconds, plus one human approval, takes four hours, because the approver is in a meeting. The ROI evaporates. You did not save the labor. You converted doing into reviewing, and the reviewer has to first understand what the agent did, which is often slower than doing it themselves.", "The conclusion is not ‘find a balance.’ It is that approval has to be graded by risk, never by action type. ‘All writes require approval’ is the easiest policy to write and the most lethal. A five-dollar refund and a fifty-thousand-dollar refund should not take the same path, and neither should updating a phone number and updating a credit limit.", "There is a less obvious consequence. Good observability is what earns you the right to approve less. If you can reconstruct every step, every argument, and where every authorization came from, you can let more run unattended. Auditing is not a tax on automation. It is the precondition.", "Which is why I would not put AgentOps third in priority. It belongs alongside the gateway — not for the dashboard, but because without an evidence chain in place, every later conversation about loosening a constraint comes down to guesswork."] },
    },
    {
      heading: { zh: "别太早抽象", en: "Don’t abstract too early" },
      body: { zh: ["“不要一上来就建平台”这句话人人都说，落到操作上通常没人执行。", "判断标准可以很粗暴：一个 Infra 组件如果没有两个以上真实使用者，它就不是 Infra，是你的兴趣爱好。", "验收也别用“回答得挺不错”。至少要有任务完成率、人工接管率、越权拦截率，还有单位业务结果的成本。最后这个最容易被跳过，也最容易在半年后变成一张没人解释得清的账单。", "还有一句可能有人不同意：不要因为一个框架“支持多 Agent”就选它。多 Agent 不是默认方案，只有当任务真的能被拆开、而且拆开的收益能被量出来的时候，才值得引入。大部分时候它带来的是调试成本，不是效果。", "至于什么时候可以开始抽象，能执行的版本大概是这样："], en: ["‘Don’t build a platform on day one’ is advice everyone gives and almost nobody follows.", "A blunt test works well enough. An infrastructure component with fewer than two real consumers is not infrastructure. It is your hobby.", "Acceptance should not be ‘the answers look pretty good’ either. At minimum: task completion rate, human takeover rate, blocked-escalation rate, and cost per unit of business outcome. That last one gets skipped most often and turns into a bill nobody can explain six months later.", "One more thing some people will disagree with. Do not pick a framework because it supports multiple agents. Multi-agent is not the default. It earns its place only when the work genuinely decomposes and the gain from decomposing it can be measured. Most of the time what it delivers is debugging cost, not capability.", "As for when to start abstracting, the followable version is roughly this:"] },
      bullets: { zh: ["第一个场景，不抽象任何东西。允许写死，允许难看。", "第二个场景，还是别抽。两个点连不出一条线。", "第三个场景出现同样的连接器、同样的审批逻辑、同样的审计要求，这时候抽，而且只抽重复出现的那部分。"], en: ["First scenario: abstract nothing. Hard-code it. Let it be ugly.", "Second scenario: still don’t. Two points do not make a line.", "Third scenario, when the same connector, the same approval logic, and the same audit requirement show up again: abstract, and only the part that repeated."] },
    },
  ],
  closing: { zh: "如果你现在只跑一个只读的知识问答，这篇文章里的东西你一样都不需要，现在建基础设施是在给一个还不存在的规模做准备。真正的分水岭是你第一次让 Agent 写生产数据那天。在那之前，它是奢侈品；过了那天，它是许可证。", en: "If all you run today is read-only Q&A, you need none of this, and building infrastructure now is preparing for a scale that does not exist yet. The dividing line is the day you first let an agent write production data. Before that day it is a luxury. After it, a license." },
} satisfies ArticleBody;

const articles: Record<string, ArticleBody | undefined> = { "agent-infra": agentInfra };

function App() {
  const [dark, setDark] = useState(false);
  const [lang, setLang] = useState<Language>("zh");
  const [query, setQuery] = useState("");
  const [activeTag, setActiveTag] = useState("全部");
  const [page, setPage] = useState<"home" | "article" | "about">("home");
  const [activeId, setActiveId] = useState(featured.id);
  const [progress, setProgress] = useState(0);
  const t = copy[lang];

  useEffect(() => { const savedTheme = window.localStorage.getItem("shihao-theme"); setDark(savedTheme === "dark"); const savedLang = window.localStorage.getItem("shihao-language"); if (savedLang === "en" || savedLang === "zh") setLang(savedLang); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; window.localStorage.setItem("shihao-theme", dark ? "dark" : "light"); }, [dark]);
  useEffect(() => { window.localStorage.setItem("shihao-language", lang); }, [lang]);
  useEffect(() => {
    if (page !== "article") return;
    const updateProgress = () => {
      const available = document.documentElement.scrollHeight - window.innerHeight;
      setProgress(available > 0 ? Math.min(100, (window.scrollY / available) * 100) : 0);
    };
    updateProgress();
    window.addEventListener("scroll", updateProgress, { passive: true });
    return () => window.removeEventListener("scroll", updateProgress);
  }, [page]);

  const tags = [t.all, ...Array.from(new Set(posts.map((post) => post.tag[lang])))];
  const filtered = useMemo(() => posts.filter((post) => (activeTag === t.all || post.tag[lang] === activeTag) && `${post.title[lang]}${post.excerpt[lang]}`.toLowerCase().includes(query.toLowerCase())), [activeTag, lang, query, t.all]);
  const showPage = (next: "home" | "article" | "about") => { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openPost = (id: string) => { setActiveId(id); showPage("article"); };
  const activePost = posts.find((post) => post.id === activeId) ?? featured;
  const activeArticle = articles[activePost.id];
  const changeLanguage = () => { setLang(lang === "zh" ? "en" : "zh"); setActiveTag(lang === "zh" ? "All" : "全部"); };
  const navToWriting = () => {
    if (page !== "home") {
      setPage("home");
      window.setTimeout(() => document.querySelector("#writing")?.scrollIntoView({ behavior: "smooth" }), 0);
    }
  };

  const Header = () => <header className="wrap"><nav className="nav site-nav" aria-label="Main navigation">
    <button className="nav-brand" onClick={() => showPage("home")}>Shihao Xiong</button>
    <button className={page === "home" ? "nav-link active" : "nav-link"} onClick={navToWriting}>{t.articles}</button>
    <button className={page === "about" ? "nav-link active" : "nav-link"} onClick={() => showPage("about")}>{t.about}</button>
    <button className="nav-link language" onClick={changeLanguage}>{lang === "zh" ? "EN" : "中文"}</button>
    <button className="btn btn-secondary theme-btn" onClick={() => setDark((value) => !value)} aria-label="Toggle color theme">{dark ? "☾ 夜" : "☀ 日"}</button>
  </nav></header>;

  const Timeline = () => <section className="timeline stack" aria-label="Timeline">
    <h6 className="section-label">{lang === "zh" ? "正在思考 / Now" : "Currently thinking"}</h6>
    <div className="tl-row"><div className="tl-rail"><i /><u /></div><div className="card tl-card"><small>NOW</small><h4>{lang === "zh" ? "Agent Infra 与企业运行边界" : "Agent infrastructure and enterprise boundaries"}</h4><p>{lang === "zh" ? "持续记录 Agent 如何安全、稳定、可治理地完成真实工作。" : "Notes on helping agents complete real work safely, reliably, and governably."}</p></div></div>
    <div className="tl-row"><div className="tl-rail"><i className="olive" /><u /></div><div className="card tl-card"><small>WRITING</small><h4>{lang === "zh" ? "把尚未成形的思考写清楚" : "Making half-formed thoughts clear"}</h4><p>{lang === "zh" ? "技术笔记与工作方法，慢慢整理，持续更新。" : "Technical notes and ways of working, gathered gradually."}</p></div></div>
  </section>;

  const Footer = () => <footer className="wrap site-footer"><span>© 2026 Shihao Xiong</span><span>{lang === "zh" ? "慢慢写，也认真写。" : "Written slowly, with care."}</span><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>{t.top}</button></footer>;

  const Home = () => <main className="wrap stack home-page">
    <section className="hero" id="top"><div className="hero-copy"><h6>SHIHAO XIONG · FIELD NOTES</h6><h1>{lang === "zh" ? "构建 Agent 基础设施，也把过程写下来。" : "Building agent infrastructure, and writing it down."}</h1><p>{lang === "zh" ? "关于企业 Agent、工程实践与慢慢形成的想法。这里记录问题如何被拆开、验证，最后变成可靠的系统。" : "Notes on enterprise agents, engineering practice, and ideas taking shape—how problems are unpacked, tested, and turned into reliable systems."}</p><div className="hero-actions"><a className="btn btn-primary" href="#writing">{lang === "zh" ? "阅读文章" : "Read notes"}</a><button className="btn btn-secondary" onClick={() => showPage("about")}>{t.about}</button></div></div><div className="portrait-ring"><img className="portrait washed" src="/images/shihao-sunset.png" alt={lang === "zh" ? "日落海面" : "Sunset over the sea"} /></div></section>
    <section className="now-bar" aria-label="Now"><h6>{lang === "zh" ? "现在" : "Now"}</h6><div className="now-item"><span className="dot" /><div><b>{lang === "zh" ? "整理 Agent Infra 的实践" : "Mapping agent infrastructure"}</b><span>{lang === "zh" ? "写作 · 进行中" : "Writing · in progress"}</span></div></div><div className="now-item"><span className="dot dot-2" /><div><b>{lang === "zh" ? "阅读与构建" : "Reading and building"}</b><span>{lang === "zh" ? "工程 · 持续进行" : "Engineering · ongoing"}</span></div></div><div className="now-item"><span className="dot dot-idle" /><div><b>{lang === "zh" ? "更新这个小站" : "Tending this small site"}</b><span>{lang === "zh" ? "博客 · 缓慢更新" : "Blog · slowly updated"}</span></div></div></section>
    <article className="card elev-sm featured"><span className="card-kicker">{lang === "zh" ? "最新一篇" : "Latest note"} · {featured.date} · {featured.minutes}</span><h2>{featured.title[lang]}</h2><p>{featured.excerpt[lang]}</p><button className="btn btn-primary" onClick={() => openPost(featured.id)}>{lang === "zh" ? "继续读 →" : "Continue reading →"}</button></article>
    <section className="cols" id="writing"><div className="col"><div className="row-between"><h6>{lang === "zh" ? "技术笔记" : "Technical notes"}</h6><span className="quiet-count">{posts.length} {lang === "zh" ? "篇" : "note"}</span></div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} aria-label={t.search} /></label><div className="filters" aria-label="Article tags">{tags.map((tag) => <button className={activeTag === tag ? "active" : ""} key={tag} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div><div className="note-list">{filtered.map((post) => <button className="note" key={post.id} onClick={() => openPost(post.id)}><span className="dot" /><span><h4>{post.title[lang]}</h4><small>{post.date} · {post.minutes}</small></span></button>)}{filtered.length === 0 && <p className="empty">{t.noResults}</p>}</div></div><div className="col"><div className="row-between"><h6 className="olive-label">{lang === "zh" ? "写作方向" : "Writing directions"}</h6></div><div className="card career-card"><h4>{lang === "zh" ? "让系统在企业里长期工作" : "Making systems work over time"}</h4><small>{lang === "zh" ? "Agent Infra · 安全与治理" : "Agent infra · safety and governance"}</small></div><div className="card career-card"><h4>{lang === "zh" ? "把复杂的工程问题说明白" : "Explaining complex engineering"}</h4><small>{lang === "zh" ? "工作方法 · 技术笔记" : "Ways of working · technical notes"}</small></div><div className="card career-card"><h4>{lang === "zh" ? "持续学习，持续校正" : "Learn, then recalibrate"}</h4><small>{lang === "zh" ? "阅读 · 观察 · 实践" : "Reading · observation · practice"}</small></div></div></section>
    <Timeline />
    <section className="band"><div><h4>{lang === "zh" ? "想聊聊，或者订阅更新" : "Say hello or follow along"}</h4><p>{lang === "zh" ? "有想法、问题或一起在做的事，欢迎来信。" : "Ideas, questions, or work in progress are always welcome."}</p></div><div className="band-actions"><a className="btn btn-primary" href="mailto:xiongshihao97@gmail.com">Email</a><button className="btn btn-secondary" onClick={() => showPage("about")}>{t.about}</button></div></section>
  </main>;

  const About = () => <main className="wrap"><div className="about-page"><aside className="about-side"><img className="portrait-lg washed" src="/images/shihao-sunset.png" alt={lang === "zh" ? "日落海面" : "Sunset over the sea"} /><a className="btn btn-secondary btn-block" href="mailto:xiongshihao97@gmail.com">Email <span>↗</span></a><button className="btn btn-secondary btn-block" onClick={() => showPage("home")}>{t.articles} <span>→</span></button></aside><div className="about-body"><section><h6>{lang === "zh" ? "关于 / About" : "About"}</h6><h1>{lang === "zh" ? "你好，我是 Shihao。" : "Hi, I’m Shihao."}</h1><p>{t.aboutLead}</p><p>{t.aboutBody}</p></section><Timeline /><section><h6 className="section-label">{lang === "zh" ? "关注" : "Focus"}</h6><div className="tag-row"><span className="tag tag-outline">Agent Infra</span><span className="tag tag-outline">Systems</span><span className="tag tag-outline">AgentOps</span><span className="tag tag-outline">Writing</span><span className="tag tag-outline">AI</span></div></section><section className="cta"><h4>{lang === "zh" ? "聊聊？" : "Let’s talk."}</h4><p>{lang === "zh" ? "关于基础设施、团队，或者一个尚未想清楚的工程问题，都欢迎写信。" : "Infrastructure, teams, or an engineering problem that is not clear yet—all welcome."}</p><a className="btn btn-primary" href="mailto:xiongshihao97@gmail.com">{lang === "zh" ? "写信给我" : "Email me"}</a></section></div></div></main>;

  const Article = () => {
    if (!activeArticle) return <main className="wrap"><div className="article"><article className="prose"><span className="tag tag-accent">{activePost.tag[lang]}</span><h1>{activePost.title[lang]}</h1><p className="lead">{t.comingSoon}</p><button className="btn btn-secondary back-button" onClick={() => showPage("home")}>← {t.back}</button></article></div></main>;
    return <><div className="progress-track"><div className="progress-bar" style={{ width: `${progress}%` }} /></div><main className="wrap"><div className="article"><aside className="aside"><button className="btn btn-secondary back-button" onClick={() => showPage("home")}>← {t.back}</button><nav className="card toc" aria-label="Table of contents"><span className="card-kicker">{lang === "zh" ? "目录" : "Contents"}</span>{activeArticle.sections.map((section, index) => <a href={`#section-${index + 1}`} key={section.heading.zh}><i>{String(index + 1).padStart(2, "0")}</i><span>{section.heading[lang]}</span></a>)}</nav><div className="card author-card"><div className="author-head"><img className="washed" src="/images/shihao-sunset.png" alt="" /><div><b>Shihao Xiong</b><span>Agent Infrastructure</span></div></div><small>{activePost.date} · {activePost.minutes}</small></div></aside><article className="prose"><span className="tag tag-accent">{activePost.tag[lang]}</span><h1>{activePost.title[lang]}</h1><p className="dek">{activeArticle.subtitle[lang]}</p><p className="lead">{activeArticle.intro[lang]}</p>{activeArticle.sections.map((section, index) => <section id={`section-${index + 1}`} key={section.heading.zh}><div className="h-num"><i>{String(index + 1).padStart(2, "0")}</i><h3>{section.heading[lang]}</h3></div>{section.body[lang].map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets[lang].map((item) => <li key={item}>{item}</li>)}</ul>}{section.figure && <figure><img src={section.figure.src} alt={section.figure.caption[lang]} /><figcaption>{section.figure.caption[lang]}</figcaption></figure>}</section>)}<p className="closing">{activeArticle.closing[lang]}</p><div className="tag-row"><span className="tag tag-outline">agent-infra</span><span className="tag tag-outline">systems</span><span className="tag tag-outline">governance</span></div></article></div></main></>;
  };

  return <div className="site-shell"><Header />{page === "home" ? <Home /> : page === "about" ? <About /> : <Article />}<Footer /></div>;
}

createRoot(document.getElementById("root")!).render(<App />);
